version: '2'
services:
    mysql-app:
        image: mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-mysql:3306/mysql?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=mysql-elasticsearch:9300
        ports:
            - 8100:8100
    mysql-mysql:
        extends:
            file: mysql.yml
            service: mysql-mysql
    mysql-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: mysql-elasticsearch
